### ISSUE TITLE
Using libzim binary on alpine

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#566] opened 2021-05-28 10:50 UTC
Trying to use libzim release on alpine, I realized we have **a ton** of missing symbols on our *static* binary.

After installing GNU's libstdc++ (`apk -U add libstdc++ gcompat`), it's better but sill… 

```
ldd lib/x86_64-linux-gnu/libzim.so.6
/libzim_linux-x86_64-6.3.0 # ldd lib/x86_64-linux-gnu/libzim.so.6
	/lib/ld-musl-x86_64.so.1 (0x7fb648dec000)
	librt.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fb648dec000)
	libpthread.so.0 => /lib/ld-musl-x86_64.so.1 (0x7fb648dec000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fb647ab1000)
	libm.so.6 => /lib/ld-musl-x86_64.so.1 (0x7fb648dec000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fb647a97000)
	libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7fb648dec000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7fb647a91000)
Error relocating lib/x86_64-linux-gnu/libzim.so.6: getdirentries: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __rawmemchr: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __strncpy_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __sprintf_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __snprintf_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __fread_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __memmove_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __strcpy_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __strcat_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: backtrace: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: backtrace_symbols: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __fprintf_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __memcpy_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: _sys_errlist: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: _sys_nerr: symbol not found
```

I know that those symbols are not implemented in musl's version but I'd expect to see those in the GNU version. Is this to be expected ?

Just trying to understand ; using it on alpine is not a requirement for me and the static cli tools do bundle everything and works fine.

**Comment by kelson42** [comment] 2021-06-08 05:07
@veloman-yunkan Maybe you can help @rgaudin on this?

**Comment by veloman-yunkan** [comment] 2021-06-19 08:53
Adding `libgcompat.so` as an explicitly declared dependency of `libzim.so` reduces the number of unresolved symbols further:

```
/opt/libzim-6.3.0 # ldd lib/x86_64-linux-gnu/libzim.so.6
	/lib/ld-musl-x86_64.so.1 (0x7fd566660000)
	librt.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fd566660000)
	libpthread.so.0 => /lib/ld-musl-x86_64.so.1 (0x7fd566660000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fd565326000)
	libm.so.6 => /lib/ld-musl-x86_64.so.1 (0x7fd566660000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fd56530c000)
	libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7fd566660000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7fd565306000)
Error relocating lib/x86_64-linux-gnu/libzim.so.6: getdirentries: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __rawmemchr: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __strncpy_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __sprintf_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __snprintf_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __fread_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __memmove_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __strcpy_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __strcat_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: backtrace: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: backtrace_symbols: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __fprintf_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: __memcpy_chk: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: _sys_errlist: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: _sys_nerr: symbol not found

/opt/libzim-6.3.0 # patchelf --add-needed libgcompat.so.0 lib/x86_64-linux-gnu/libzim.so.6

/opt/libzim-6.3.0 # ldd lib/x86_64-linux-gnu/libzim.so.6
	/lib/ld-musl-x86_64.so.1 (0x7f53cfb0b000)
	libgcompat.so.0 => /lib/libgcompat.so.0 (0x7f53ce8cb000)
	librt.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f53cfb0b000)
	libpthread.so.0 => /lib/ld-musl-x86_64.so.1 (0x7f53cfb0b000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f53ce72a000)
	libm.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f53cfb0b000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f53ce710000)
	libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f53cfb0b000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f53ce70a000)
	libucontext.so.1 => /lib/libucontext.so.1 (0x7f53ce705000)
	libobstack.so.1 => /usr/lib/libobstack.so.1 (0x7f53ce700000)
Error relocating lib/x86_64-linux-gnu/libzim.so.6: getdirentries: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: _sys_errlist: symbol not found
Error relocating lib/x86_64-linux-gnu/libzim.so.6: _sys_nerr: symbol not found
```

**Comment by veloman-yunkan** [comment] 2021-06-19 09:36
I think that the deprecated/non-standard symbols `_sys_errlist` and `_sys_nerr` can be eliminated from `libzim.so` by replacing the few calls to `perror()` with `strerror()`.

Not sure where `getdirentries()` comes from.

**Comment by kelson42** [comment] 2021-06-19 11:53
@mgautierfr Can we go forward with @veloman-yunkan propositions?

**Comment by mgautierfr** [comment] 2021-07-07 15:00
The problem is that we are building libzim with glibc and we try to link it with musl. (I suppose every know already agree on this here)

- All the `__*_chk` symbol seems to come from the compilation with _FORTIFY_SOURCE (which is added by meson) (see https://stackoverflow.com/questions/55246192/musl-gcc-undefined-reference-to-memcpy-chk)
- getdirentries comes from xapian (`common/closefrom.c`). It seems it has some conditional compilation for this as bionic doesn't have getdirentries neither. But as we are compiling with glibc, it uses it.

The best is probably to build libzim on musl if we want to run it with musl.

> @mgautierfr Can we go forward with @veloman-yunkan propositions?

For replacing `perror()` with `strerror()` yes.

Adding `libgcompat.so` probably not. We would need to have libgcompat available even on platform where it is not needed (if it is available)

For `getdirentries()` we have to investigate the impact of compiling xapian without it.

**Comment by kelson42** [comment] 2021-07-13 11:08
To my opinion, there is nothing reasonable we can do here. The solution here is not only to provide libzim compiled against musl, but the whole toolchain as well (at least python-libzim here), but we could think as well of zim-tools, libkiwix, etc... I don't think we should foloow that path. @rgaudin Would you agree to fix this ticket as WONTFIX?

**Comment by rgaudin** [comment] 2021-07-13 11:12
> To my opinion, there is nothing reasonable we can do here. The solution here is not only to provide libzim compiled against musl, but the whole toolchain as well (at least python-libzim here), but we could think as well of zim-tools, libkiwix, etc... I don't think we should foloow that path.

As stated in the ticket, the static cli binaries work properly on Alpine. What doesn't is building/linking on Alpine.

> @rgaudin Would you agree to fix this ticket as WONTFIX?

Sure, would have been a nice to have for me but I can live without it. Required effort doesn't seem worth it for now.

**Closed** 2021-07-13 11:13 UTC
Labels: question
