### ISSUE TITLE
wikiHow has broken suggestions with latest stable Kiwix release

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#624] opened 2021-09-08 07:08 UTC
Playing with https://mirror.download.kiwix.org/zim/.hidden/dev/wikihow_tr_all_2021-09.zim.

The suggestions don't work at all with:
* latest Kiwix-Desktop 2.0.5: I get a blank page when I click on a suggestion
* latest Kiwix-Serve 3.1.2-5: A fulltext search is started when I click on a suggestion.

This does look like a bug to me.

**Comment by kelson42** [comment] 2021-09-08 07:08
@maneeshpm Would you be able please to have a look?

**Comment by maneeshpm** [comment] 2021-09-08 07:51
@kelson42 It seems to be working on latest libzim/libkiwix :confused: 
![Screenshot from 2021-09-08 13-19-26](https://user-images.githubusercontent.com/45821104/132468777-9a98a940-a888-468e-b39b-f24299cb9436.png)
Can you confirm the issue?

**Comment by kelson42** [comment] 2021-09-08 14:38
@maneeshpm Yes it does, sorry for not mentioning this.

**Comment by maneeshpm** [comment] 2021-09-20 17:22
@kelson42 As far as I have tested, Suggestion seems to be working fine on libzim/libkiwix github master on the given zim file. What exactly is the issue that we need to investigate?

**Comment by kelson42** [comment] 2021-09-20 18:21
@maneeshpm latest stable releases... the ones actually on production.

**Comment by mgautierfr** [comment] 2021-09-22 08:42
To be clear, we are testing a "new" zim file (created with not yet (but soon) released version of libzim) with a "old" reader (released libzim).

We have to investigate what happen. Do we wrongly create the zim file ? Are we ok with this or do we want to fix the creation process before releasing ?

**Comment by maneeshpm** [comment] 2021-09-22 15:46
@kelson42 I am testing against libzim 6.3.0(17 nov) / libkiwix 9.4.1 (17 nov) / kiwix-tools 3.1.2(2 jul 2020) and suggestions seems to be working for me. Can you confirm these versions?

![Screenshot from 2021-09-22 21-08-42](https://user-images.githubusercontent.com/45821104/134376879-14eb445b-74c3-4c85-a3c7-9aaac223cc79.png)

**Comment by maneeshpm** [comment] 2021-09-22 17:42
@kelson42 @mgautierfr aaha found the issue! This is going to be a nasty one.

This has actually to do with the way we "handle content" in the new and the old libzim. In the new libkiwix we directly use the `path` key of the suggestions json to get the "clicked" suggestion. But in older libkiwix, we don't have this key, all we have is the `label`(which is same as the `title`). So to get the clicked suggestion, we call `handle_search` on the title, and in the function, we call `Reader::getEntryFromTitle()` on all the variants of the title which in turn calls `zim::File::getArticleByTitle(ns, title)` on the variants. If a match is found, we are returned the content, otherwise we proceed to a full text search.

Now, the `Reader::getEntryFromTitle()` calls the `zim::File::getArticleByTitle(ns, title)` on `"A" `namespace following the old convention, hence things work normally for older zim `wikipedia_en_all_mini_2021-01.zim`. But for newer zim `wikihow_tr_all_2021-09.zim`, we have everything in the `"C"` namespace and hence, the search fails. This can be confirmed by forcing a search on `"C"` namespace by the reader(by editing the code).

We need to do something about the namespace compatibility layer to fix this. @mgautierfr any idea how to proceed?

**Comment by mgautierfr** [comment] 2021-09-23 09:34
Well, we have a tool that explicitly search something in "A" namespace where the content is in "C" namespace. This obviously can't work.
I see 3 "solutions" :

- Move back the content from `C` namespace in `A` namespace. I somehow dislike this idea. This means a lot of rewriting/testing of libzim (where we are/were pretty close to release it). And all zim file created with master would be invalid.
- Do nothing. Old kiwix-serve will not be able to do a suggestion on new zim file. Update your tools and you are good. This is the laziest solution, but we would do a release of all our tools in the same time to be able to tell our users to use last tool.
- Add a small forward compatibility (for zim file which don't officially exists) in libkiwix to also search on `C` namespace. It would be a fix release based on the current release. The user still would have to update the tools to make this work but as we would release the tools a bit in advance, we have more chance that when we release the new libzim (and zim files), users already have a tool working and the transition would be (more) silent.

My preference goes to the third option.

**Comment by kelson42** [comment] 2021-09-23 10:13
I believe there is nothing much we can do, should do. Considering that we are anyway going to release new version of libkiwix very soon. The only way to fix this would require to create new ZIM files which somehow work fine with older/current Kiwix. This seems not possible. Therefore, I would just close this as WONTFIX.

**Comment by rgaudin** [comment] 2021-09-23 10:18
Agrees with @kelson42. Is it worth creating a `known-bug` label for later reference or is it the only issue we have?

**Comment by maneeshpm** [comment] 2021-09-24 03:36
I agree with @kelson42, anything we do to patch this issue will introduce a new layer of *unwanted* complications.  Closing this as wontfix. @rgaudin `known-bug` is a good tag to have!

**Closed** 2021-09-24 03:37 UTC
Labels: bug, wontfix, search
