### ISSUE TITLE
Missing suggestion result

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#474] opened 2021-01-19 16:04 UTC
Couldn't find any open ticket regarding this…

Testing with this tiny [test3.zim.zip](https://github.com/openzim/libzim/files/5837011/test3.zim.zip).

It has two `text/plain` articles with

| path | title | content |
---|---|---|
| `accueil` | `a nice house` | `accueil` |
| `home` | `a nice house` | `welcome` |

Searching the content works fine.

```py
list(zim.search("nice"))
> ['accueil', 'home']
```

Getting suggestions doesn't:

```py
list(zim.suggest("nice"))
> ['accueil']

list(zim.suggest("house"))
> ['accueil']
```

We only receive one suggestion while we should get two.

**Comment by kelson42** [comment] 2021-01-20 14:15
We can not release libzim7 with this being unclear/unfixed.

**Comment by kelson42** [comment] 2021-01-24 12:26
I steongly suspect that this is the same root cause as #471

**Comment by kelson42** [comment] 2021-03-12 05:56
@mgautierfr Is https://github.com/openzim/zim-tools/issues/230 a duplicate of this one?

**Comment by maneeshpm** [comment] 2021-03-13 04:53
Seems to be a result of [this](https://github.com/openzim/libzim/blob/0dffcaba659f07f17a6293fedaa9403b1220240f/src/search.cpp#L399-L401), we are performing a collapse on title in suggestion mode
```c++
    if (suggestion_mode && valuesmap.find("title") != valuesmap.end()) {
      enquire.set_collapse_key(valuesmap["title"]);
    }
```
Articles with the same title collapse into one result which has the highest relevance. Is this a feature we want to keep?

**Comment by kelson42** [comment] 2021-03-13 05:49
@maneeshpm I believe no, but we need to identify the ticket/PR for which this code has been introduced in a first place.

**Comment by maneeshpm** [comment] 2021-03-13 05:54
Introduced here #274

**Comment by kelson42** [comment] 2021-03-13 06:17
@maneeshpm If @mgautierfr agrees, I believe we can remove it. Considering the patch is trivial, you can make it and ask him to review.

**Closed** 2021-03-15 13:21 UTC
Labels: bug, search
