### ISSUE TITLE
Created search index is unusable

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#481] opened 2021-01-26 14:30 UTC
I don't think it's related to  #471 but I'm not familiar with the internals of search.

I am using python-libzim (next) so consider the possibility of a bug there though code is very limited (a call to cpp `.configIndex(indexing, language)`) and seems OK and `test/` doesn't seem to test this.

Creating simple zim with indexing for `eng` and adding a single Item at `lorem_ipsum` with `text/html` and the following content:

```html
<html><head><title>Lorem Ipsum</title></head><body><h2>What is Lorem Ipsum?</h2> <p><strong>Lorem Ipsum</strong> issimply dummy text of the printing and typesetting industry. LoremIpsum has been the industry's standard dummy text ever since the1500s, when an unknown printer took a galley of type and scrambled itto make a type specimen book. It has survived not only five centuries,but also the leap into electronic typesetting, remaining essentiallyunchanged. It was popularised in the 1960s with the release ofLetraset sheets containing Lorem Ipsum passages, and more recentlywith desktop publishing software like Aldus PageMaker includingversions of Lorem Ipsum.</p> </div><div> <h2>Why do we use it?</h2><p>It is a long established fact that a reader will be distracted bythe readable content of a page when looking at its layout. The pointof using Lorem Ipsum is that it has a more-or-less normal distributionof letters, as opposed to using 'Content here, content here', makingit look like readable English. Many desktop publishing packages andweb page editors now use Lorem Ipsum as their default model text, anda search for 'lorem ipsum' will uncover many web sites still in theirinfancy. Various versions have evolved over the years, sometimes byaccident, sometimes on purpose (injected humour and the like).</p></div><br><div> <h2>Where does it come from?</h2> <p>Contrary topopular belief, Lorem Ipsum is not simply random text. It has roots ina piece of classical Latin literature from 45 BC, making it over 2000years old. Richard McClintock, a Latin professor at Hampden-SydneyCollege in Virginia, looked up one of the more obscure Latin words,consectetur, from a Lorem Ipsum passage, and going through the citesof the word in classical literature, discovered the undoubtablesource. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "deFinibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero,written in 45 BC. This book is a treatise on the theory of ethics,very popular during the Renaissance. The first line of Lorem Ipsum,"Lorem ipsum dolor sit amet..", comes from a line in section1.10.32.</p><p>The standard chunk of Lorem Ipsum used since the 1500sis reproduced below for those interested. Sections 1.10.32 and 1.10.33from "de Finibus Bonorum et Malorum" by Cicero are also reproduced intheir exact original form, accompanied by English versions from the1914 translation by H. Rackham.</p> </div><div> <h2>Where can I getsome?</h2> <p>There are many variations of passages of Lorem Ipsumavailable, but the majority have suffered alteration in some form, byinjected humour, or randomised words which don't look even slightlybelievable. If you are going to use a passage of Lorem Ipsum, you needto be sure there isn't anything embarrassing hidden in the middle oftext. All the Lorem Ipsum generators on the Internet tend to repeatpredefined chunks as necessary, making this the first true generatoron the Internet. It uses a dictionary of over 200 Latin words,combined with a handful of model sentence structures, to generateLorem Ipsum which looks reasonable. The generated Lorem Ipsum istherefore always free from repetition, injected humour, ornon-characteristic words etc.</p> </body></html>
```

This gets me [lolo.zim](https://github.com/openzim/libzim/files/5873885/lolo.zim.zip)

Now inserting this exact HTML content in a file named `lorem_ipsum.html` (plus a favicon) and creating a ZIM with zimwriterfs (2.1.0), I get [lorem.zim](https://github.com/openzim/libzim/files/5873890/lorem.zim.zip)

---

testing both with pylibzim reader

```py
from libzim.reader import Archive

bad = Archive("lolo.zim")
list(good.search("standard"))
> []
bad.get_entry_by_id(1)
> Entry(url=fulltext/xapian, title=fulltext/xapian)
bad.get_entry_by_id(1).get_item().size
> 24576

good = Archive("lorem.zim")
list(good.search("standard"))
> ['A/lorem_ipsum.html']
good.get_entry_by_id(15)
> Entry(url=X/fulltext/xapian, title=Xapian Fulltext Index)
good.get_entry_by_id(15).get_item().size
> 32768
```

As you can see, I can't get any search result from the manually created zim file yet there is a 24k xapian index (maybe it's only overhead?).
On the other hand, the zimwriterfs created one returns the article for every word in that document. It has a 32k xapian index.

**Comment by mgautierfr** [comment] 2021-01-28 13:27
Pr #466 seems to fix the issue but nothing is especially done to fix it (just that we rewrite a bit how we create the index).
As we will split the PR, we will need to test again the issue to be sure it is fixed.

**Comment by maneeshpm** [comment] 2021-03-21 06:50
I was able to recreate this issue on the latest master as well. The peculiar thing is when the content of the item is plain text, the item gets added (archive.getEntryCount() returns 2) and the indexing is working fine, we can search on it. When the content is an html (inside double quotes), the item isn't being added at all, and in that case, the index is unusable. 
I think this is not exactly a bug but an implementation issue. Is there any preprocessing that needs to be done when adding html content compared to when adding regular string content?

This is working
```c++
    auto item = std::make_shared<TestItem1>("lorem_ipsum", "Lorem Ipsum", "this is a standard text");
```

This is not working
```c++
    auto item = std::make_shared<TestItem1>("lorem_ipsum", "Lorem Ipsum", "<html><head><title>Lorem Ipsum</title></head><body> ... </body></html>");
```
Where `TestItem1` is an extension of `writer::Item` with a string content provider similar to [this](https://github.com/openzim/libzim/blob/d4801b64386ee71994c0edb56ba9b00fcf93013f/test/creator.cpp#L156-L175)

**Comment by kelson42** [comment] 2021-03-21 07:28
@maneeshpm Sounds like a duplicate of #519. Html is parsed to exctract the words and @mgautierfr has discovered that for some reason this process now fails.

**Comment by mgautierfr** [comment] 2021-03-30 12:46
Yes, @maneeshpm please test with https://github.com/openzim/libzim/pull/522. Hope it will fix this issue.

**Closed** 2021-04-15 13:50 UTC
Labels: bug
